resolver: nightly-2019-05-25

packages:
- '.'

extra-deps:

- bioinformatics-toolkit-0.9.2
- HsHTSLib-1.9.2
- bbi-0.1.1
- clustering-0.4.1
- git:     https://github.com/kaizhang/matrix-sized.git
  commit:  c58c2ccae708226faab1dce9545364a39f5a2076

flags:
  matrix-sized:
    parallel: true
